### ISSUE TITLE
朋友是一个坚韧不拔的纪录片

### ISSUE THREAD

**Issue by YoDobchev** [CatsArePanzers/python_project#2]
在香港这座城市的设置。 主演：钱德勒 索罗斯 傅博斯1 瑞秋 莫妮卡 和一些其他他妈的演员

**Comment by YoDobchev** [comment]
你也能帮我把我父亲从监狱里释放出来吗？

**Comment by kamenpopov** [comment]
游戏有效！！！！！

**Comment by CatsArePanzers** [comment]
Wǒ zuì xǐhuān de shì luósī, tā yǒu xiàndài dòngmàn de bóshì xuéwèi
